# Generated by Django 4.2.3 on 2023-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_production',
            field=models.DateField(null=True),
        ),
    ]
